package com.zhidisoft.bos.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-15T22:37:07.883+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://cxfservice.huawei.com/", name = "CXFService")
@XmlSeeAlso({
	//ObjectFactory.class
	})
public interface CXFService {

    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://cxfservice.huawei.com/", className = "Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findByTelePhone", targetNamespace = "http://cxfservice.huawei.com/", className = "FindByTelePhone")
    @ResponseWrapper(localName = "findByTelePhoneResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "FindByTelePhoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Customer findByTelePhone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findNoSocciated", targetNamespace = "http://cxfservice.huawei.com/", className = "FindNoSocciated")
    @ResponseWrapper(localName = "findNoSocciatedResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "FindNoSocciatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findNoSocciated();

    @WebMethod
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://cxfservice.huawei.com/", className = "FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "FindDecidedzoneIdByAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String findDecidedzoneIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findSocciatedById", targetNamespace = "http://cxfservice.huawei.com/", className = "FindSocciatedById")
    @ResponseWrapper(localName = "findSocciatedByIdResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "FindSocciatedByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findSocciatedById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://cxfservice.huawei.com/", className = "FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://cxfservice.huawei.com/", className = "FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Customer> findAll();
}
